'''
Django settings for pharmadex project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
'''

import os
import importlib.util
from datetime import timedelta
from pathlib import Path
from decouple import config
import dj_database_url
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------------------------------------
# Environment selector
# --------------------------------------------------
ENVIRONMENT = config('ENVIRONMENT', default='local')


def _cfg(key, default=None, cast=None):
    if ENVIRONMENT in ('prod', 'stage') and default is not None:
        return config(key, cast=cast) if cast is not None else config(key)
    return config(key, default=default, cast=cast) if cast is not None else config(key, default=default)


# --------------------------------------------------
# Select correct SITE_URL depending on environment
# --------------------------------------------------
SITE_URL = _cfg('SITE_URL', default='localhost:8000')


# --------------------------------------------------
# Secrets
# --------------------------------------------------
SECRET_KEY = _cfg('SECRET_KEY', default='dev-insecure-secret-key')
HASHIDS_SALT = _cfg('HASHIDS_SALT', default='dev-insecure-hashids-salt')
QR_FERNET_KEY = _cfg(
    'QR_FERNET_KEY', default='SVmnxQr0eWJc8H5YrFMOJyYH06kcD3imm1LHOwkzblI=')
DEBUG = _cfg('DEBUG', default=(
    ENVIRONMENT not in ('prod', 'stage')), cast=bool)

# --------------------------------------------------
# Hosts
# --------------------------------------------------
if ENVIRONMENT in ('local', 'local_prod'):
    ALLOWED_HOSTS = [
        'localhost',
        '127.0.0.1',
        '.ngrok-free.app',
    ]
else:
    # Production: allow Render domain + any configured SITE_URL
    ALLOWED_HOSTS = [
        'localhost',  # fallback
    ]

# Add SITE_URL if configured
if SITE_URL and SITE_URL != 'localhost:8000':
    ALLOWED_HOSTS.append(SITE_URL)
    ALLOWED_HOSTS.append(f'.{SITE_URL}')  # allow subdomains

# Render auto-injects RENDER_EXTERNAL_HOSTNAME
RENDER_HOST = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_HOST:
    ALLOWED_HOSTS.append(RENDER_HOST)

# Also allow wildcard for Render previews (remove this once stable)
if ENVIRONMENT == 'stage':
    ALLOWED_HOSTS.append('*')


# --------------------------------------------------
# CORS
# --------------------------------------------------
CORS_ALLOWED_ORIGINS = []

if ENVIRONMENT in ('local', 'local_prod'):
    CORS_ALLOWED_ORIGINS.extend([
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ])
    if SITE_URL and SITE_URL != 'localhost:8000':
        CORS_ALLOWED_ORIGINS.append(f'http://{SITE_URL}')

if ENVIRONMENT in ('stage', 'prod'):
    if SITE_URL and SITE_URL != 'localhost:8000':
        CORS_ALLOWED_ORIGINS.append(f'https://{SITE_URL}')
    # Allow Render preview URLs
    if RENDER_HOST:
        CORS_ALLOWED_ORIGINS.append(f'https://{RENDER_HOST}')


# --------------------------------------------------
# CSRF
# --------------------------------------------------
CSRF_TRUSTED_ORIGINS = []

if ENVIRONMENT in ('local', 'local_prod'):
    CSRF_TRUSTED_ORIGINS.extend([
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ])
    if SITE_URL and SITE_URL != 'localhost:8000':
        CSRF_TRUSTED_ORIGINS.append(f'http://{SITE_URL}')
        CSRF_TRUSTED_ORIGINS.append(f'https://{SITE_URL}')

if ENVIRONMENT in ('stage', 'prod'):
    if SITE_URL and SITE_URL != 'localhost:8000':
        CSRF_TRUSTED_ORIGINS.append(f'https://{SITE_URL}')
    if RENDER_HOST:
        CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_HOST}')


# --------------------------------------------------
# CSRF
# --------------------------------------------------
X_FRAME_OPTIONS = 'SAMEORIGIN'
CSP_DEFAULT_SRC = ('self',)  # Allow content to load from the same origin
CSP_FRAME_ANCESTORS = ('self',)  # Allow framing from the same origin


# --------------------------------------------------
# Application definition
# --------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # ---------third party apps-----------
    'rosetta',
    'phonenumber_field',
    'import_export',
    'simple_history',
    'auditlog',
    # 'django_htmx',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    # ---------project apps-----------
    'base.apps.BaseConfig',
    'accounts.apps.AccountsConfig',
    'organizations.apps.OrganizationsConfig',
    'pharmacies.apps.PharmaciesConfig',
    'clinics.apps.ClinicsConfig',
    'finances.apps.FinancesConfig',
    'support.apps.SupportConfig',
    'api.apps.ApiConfig',
    'website.apps.WebsiteConfig',
    # 'hr.apps.HrConfig',
    # 'notifications.apps.NotificationsConfig',
]


MIDDLEWARE = [
    # 'pharmadex.middleware.router.HostRoutingMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # must come before LocaleMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    # should come before CommonMiddleware
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'pharmadex.middleware.tenant.TenantContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pharmadex.middleware.accounts.ForcePasswordChangeMiddleware',
    'pharmadex.middleware.redirector.CurrentOrganizationMiddleware',
    # 'pharmadex.middleware.session_police.RequireSessionKeyMiddleware',
]

ROOT_URLCONF = 'pharmadex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pharmadex.config.sidebar.sidebar_context',
                'website.context_processors.country_currency',
            ],
            'builtins': ['django.templatetags.i18n'],
        },
    },
]

WSGI_APPLICATION = 'pharmadex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# RENDER POSTGRES DB
if ENVIRONMENT == 'prod':
    DATABASE_URL = config('INTERNAL_DB_URL')

    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=60)
    }
elif ENVIRONMENT == 'local_prod':
    DATABASE_URL = _cfg('EXTERNAL_DB_URL', default='')
    if DATABASE_URL:
        DATABASES = {
            'default': dj_database_url.parse(DATABASE_URL, conn_max_age=60)
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

elif ENVIRONMENT == 'stage':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'stage_db.sqlite3',
        }

    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }

    }

DATABASES["default"]["CONN_HEALTH_CHECKS"] = True


# POSTGRES DB
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'pharmadex_db',
#         'USER': 'pharmadex',
#         'PASSWORD': 'password',
#         'HOST': 'localhost',
#         'PORT': '5432',
#    }
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

USE_I18N = True
USE_L10N = True
LANGUAGE_CODE = 'en'  # Default language

# Add translation languages
LANGUAGES = [
    ('en', _('English')),
    ('fr', _('Français')),
    ('es', _('Espanol')),
    ('po', _('Portugues')),
]

# Path to pharmacy translations
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

ROSETTA_REQUIRES_AUTH = True

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Email server setup
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # SMTP mailer
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' #console mailer
EMAIL_HOST = _cfg('EMAIL_HOST', default='')
EMAIL_PORT = _cfg('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = _cfg('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = _cfg('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = _cfg('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = _cfg('DEFAULT_FROM_EMAIL', default='no-reply@localhost')
TEST_RECIPIENT_EMAIL = _cfg('TEST_RECIPIENT_EMAIL', default='')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Media files - use persistent disk path on Render, local otherwise
if ENVIRONMENT == 'prod':
    # Render disk mount point (you'll create this in dashboard)
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.environ.get('RENDER_DISK_PATH', '/var/data/media')
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Use simpler storage for Render free tier (avoid manifest issues)
if ENVIRONMENT == 'prod':
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'


# Logging avancé (console + fichier app.log)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'app.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}


AUTHENTICATION_BACKENDS = (
    # Add the path to your custom backend
    'accounts.auth_backend.EmailPhoneBackend',
    # Default backend for other auth scenarios
    'django.contrib.auth.backends.ModelBackend',
)


# very important for overiding the default user model!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
AUTH_USER_MODEL = 'accounts.CustomUser'  # !!! very important !!!

# REST Framework (API mobile)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}
