# Generated by Django 5.2.1 on 2026-05-08 17:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEncounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('encounter_number', models.CharField(max_length=50, unique=True, verbose_name='Encounter Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('chief_complaint', models.TextField(blank=True, null=True, verbose_name='Chief Complaint')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Clinical Notes')),
                ('encounter_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Encounter Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization', verbose_name='Related Organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_encounters', to='organizations.customer', verbose_name='Patient')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='pharmacies.pharmacy', verbose_name='Related Pharmacy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Clinical Encounter',
                'verbose_name_plural': 'Clinical Encounters',
                'ordering': ('-encounter_date',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('service_type', models.CharField(choices=[('consultation', 'Consultation'), ('injection', 'Injection'), ('procedure', 'Procedure'), ('minor_surgery', 'Minor Surgery (e.g. Suturing)'), ('test', 'Diagnostic Test'), ('nursing', 'Nursing Care'), ('follow_up', 'Follow Up'), ('other', 'Other')], default='other', max_length=30, verbose_name='Service Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization', verbose_name='Related Organization')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='pharmacies.pharmacy', verbose_name='Related Pharmacy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Clinical Service',
                'verbose_name_plural': 'Clinical Services',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='Diagnosis')),
                ('icd_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='ICD Code')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('diagnosed_at', models.DateTimeField(auto_now_add=True, verbose_name='Diagnosed At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='clinics.clinicalencounter', verbose_name='Clinical Encounter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization', verbose_name='Related Organization')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='pharmacies.pharmacy', verbose_name='Related Pharmacy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
                'ordering': ('-diagnosed_at',),
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('follow_up_date', models.DateTimeField(verbose_name='Follow Up Date')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Status')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='clinics.clinicalencounter', verbose_name='Clinical Encounter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization', verbose_name='Related Organization')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='pharmacies.pharmacy', verbose_name='Related Pharmacy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Follow Up',
                'verbose_name_plural': 'Follow Ups',
                'ordering': ('-follow_up_date',),
            },
        ),
        migrations.CreateModel(
            name='Injection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('dosage', models.CharField(max_length=255, verbose_name='Dosage')),
                ('route', models.CharField(max_length=100, verbose_name='Administration Route')),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Injection Site')),
                ('administered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Administered At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injections', to='clinics.clinicalencounter', verbose_name='Clinical Encounter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization', verbose_name='Related Organization')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='pharmacies.pharmacy', verbose_name='Related Pharmacy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='injections', to='pharmacies.product', verbose_name='Medication')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Injection',
                'verbose_name_plural': 'Injections',
                'ordering': ('-administered_at',),
            },
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('note', models.TextField(verbose_name='Note')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='clinics.clinicalencounter', verbose_name='Clinical Encounter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization', verbose_name='Related Organization')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='pharmacies.pharmacy', verbose_name='Related Pharmacy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Nursing Note',
                'verbose_name_plural': 'Nursing Notes',
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.CreateModel(
            name='PatientVital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperature (°C)')),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Systolic Blood Pressure')),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Diastolic Blood Pressure')),
                ('pulse_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pulse Rate')),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Respiratory Rate')),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Oxygen Saturation (%)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height (cm)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_vitals', to='clinics.clinicalencounter', verbose_name='Clinical Encounter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization', verbose_name='Related Organization')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='pharmacies.pharmacy', verbose_name='Related Pharmacy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Vital',
                'verbose_name_plural': 'Vitals',
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('procedure_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Procedure Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Procedure Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='clinics.clinicalencounter', verbose_name='Clinical Encounter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization', verbose_name='Related Organization')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='pharmacies.pharmacy', verbose_name='Related Pharmacy')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='clinics.clinicalservice', verbose_name='Clinical Service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Procedure',
                'verbose_name_plural': 'Procedures',
                'ordering': ('-procedure_date',),
            },
        ),
    ]
