# Generated by Django 5.2.1 on 2026-05-09 11:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('organizations', '0001_initial'),
        ('pharmacies', '0003_pharmacy_clinic_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('opening_hours', models.TextField(blank=True, null=True, verbose_name='Opening Hours')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization', verbose_name='Related Organization')),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='pharmacies.pharmacy', verbose_name='Related Pharmacy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
            },
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='clinics.clinic', verbose_name='Clinic'),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.clinic', verbose_name='Clinic'),
        ),
        migrations.CreateModel(
            name='ClinicalObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperature (°C)')),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Systolic Blood Pressure')),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Diastolic Blood Pressure')),
                ('pulse_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pulse Rate')),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Respiratory Rate')),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Oxygen Saturation (%)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height (cm)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_observations', to='clinics.clinicalencounter', verbose_name='Clinical Encounter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization', verbose_name='Related Organization')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='pharmacies.pharmacy', verbose_name='Related Pharmacy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Vital',
                'verbose_name_plural': 'Vitals',
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.DeleteModel(
            name='PatientVital',
        ),
    ]
