# Generated by Django 5.2.1 on 2026-05-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_remove_historicalpurchasedelivery_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='clinic_enabled',
            field=models.BooleanField(default=True, verbose_name='Clinic Enabled'),
        ),
    ]
