# Generated by Django 5.2.1 on 2026-05-09 20:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('pharmacies', '0003_pharmacy_clinic_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='cashier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cashier'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='insurance_applied',
            field=models.BooleanField(default=False, verbose_name='Insurrance Applied'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='insurance_coverage_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentage Covered'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='insurance_max_coverage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maximum Amount Covered'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='insurance_policy',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.insurancepolicy', verbose_name='Insurance Policy'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='requires_cashier_validation',
            field=models.BooleanField(default=False, verbose_name='Requires Cashier Validation'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_sales', to=settings.AUTH_USER_MODEL, verbose_name='Cashier'),
        ),
        migrations.AddField(
            model_name='sale',
            name='insurance_applied',
            field=models.BooleanField(default=False, verbose_name='Insurrance Applied'),
        ),
        migrations.AddField(
            model_name='sale',
            name='insurance_coverage_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentage Covered'),
        ),
        migrations.AddField(
            model_name='sale',
            name='insurance_max_coverage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maximum Amount Covered'),
        ),
        migrations.AddField(
            model_name='sale',
            name='insurance_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='organizations.insurancepolicy', verbose_name='Insurance Policy'),
        ),
        migrations.AddField(
            model_name='sale',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.CreateModel(
            name='SaleValidationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization', verbose_name='Related Organization')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='pharmacies.pharmacy', verbose_name='Related Pharmacy')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacies.sale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
