# Generated by Django 5.2.1 on 2026-05-12 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('pharmacies', '0004_historicalsale_cashier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalinventoryaudititem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Inventory Audit Item', 'verbose_name_plural': 'historical Inventory Audit Items'},
        ),
        migrations.AlterModelOptions(
            name='historicalinventorymovementitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Inventory Movement Item', 'verbose_name_plural': 'historical Inventory Movement Items'},
        ),
        migrations.AlterModelOptions(
            name='inventoryaudititem',
            options={'ordering': ('product_stock__product__name',), 'verbose_name': 'Inventory Audit Item', 'verbose_name_plural': 'Inventory Audit Items'},
        ),
        migrations.AlterModelOptions(
            name='inventorymovementitem',
            options={'verbose_name': 'Inventory Movement Item', 'verbose_name_plural': 'Inventory Movement Items'},
        ),
        migrations.AlterModelOptions(
            name='prescriptionitem',
            options={'verbose_name': 'Prescription Item', 'verbose_name_plural': 'Prescription Items'},
        ),
        migrations.AlterModelOptions(
            name='productalternative',
            options={'verbose_name': 'Product Alternative', 'verbose_name_plural': 'Product Alternatives'},
        ),
        migrations.AlterModelOptions(
            name='productbatch',
            options={'verbose_name': 'Product Batch', 'verbose_name_plural': 'Product Batches'},
        ),
        migrations.AlterModelOptions(
            name='productstock',
            options={'verbose_name': 'Product Stock', 'verbose_name_plural': 'Product Stocks'},
        ),
        migrations.AlterModelOptions(
            name='salevalidationlog',
            options={'verbose_name': 'Sale Validation Log', 'verbose_name_plural': 'Sale Validation Logs'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
