# Generated by Django 5.2.1 on 2026-05-14 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('pharmacies', '0005_alter_historicalinventoryaudititem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='Organization'),
        ),
    ]
