# Generated by Django 5.2.1 on 2026-05-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0006_productsubcategory_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='state_or_region',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='State / Region'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('on_credit', 'On Credit'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='clinic_enabled',
            field=models.BooleanField(default=False, verbose_name='Clinic Enabled'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('on_credit', 'On Credit'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
