# Generated by Django 5.2.1 on 2026-05-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0007_pharmacy_city_pharmacy_state_or_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('backordered', 'Backordered'), ('on_credit', 'On Credit'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('backordered', 'Backordered'), ('on_credit', 'On Credit'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
