# Generated by Django 5.2.1 on 2026-05-16 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_operationaccount_and_more'),
        ('pharmacies', '0008_alter_historicalsale_status_alter_sale_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsupplierinvoice',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='delivery',
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='cash_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finances.operationaccount'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='is_on_credit',
            field=models.BooleanField(default=False, verbose_name='On Credit'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finances.operationaccount'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_on_credit',
            field=models.BooleanField(default=False, verbose_name='On Credit'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('backordered', 'Backordered'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('backordered', 'Backordered'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
