# Generated by Django 5.2.1 on 2026-05-17 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_currency_options_remove_currency_is_default_and_more'),
        ('organizations', '0002_organization_city_organization_country_and_more'),
        ('pharmacies', '0009_remove_historicalsupplierinvoice_delivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Defaults to organization currency if not set.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacies', to='finances.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='batch_number',
            field=models.CharField(max_length=50, verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='expiry_date',
            field=models.DateField(verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='is_damaged',
            field=models.BooleanField(default=False, verbose_name='Damaged'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Manufacturing Date'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['product_stock', 'is_active'], name='pharmacies__product_946830_idx'),
        ),
    ]
