# Generated by Django 5.2.1 on 2026-05-08 18:34

import accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
        ('pharmacies', '0002_remove_historicalpurchasedelivery_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_organizations',
            field=models.ManyToManyField(blank=True, related_name='allowed_organizations', to='organizations.organization', verbose_name='Allowed organizations'),
        ),
        migrations.AddField(
            model_name='profile',
            name='allowed_pharmacies',
            field=models.ManyToManyField(blank=True, to='pharmacies.pharmacy', verbose_name='Allowed pharmacies'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_profiles', to='organizations.organization', verbose_name='Current Organization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_profiles', to='pharmacies.pharmacy', verbose_name='Current Pharmacy'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='organizations.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='accounts.role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role', 'organization')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='current_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_roles', to='accounts.userrole', verbose_name='Current Role'),
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('receiver_email', models.EmailField(max_length=254, verbose_name='Receiver Email')),
                ('user_type', models.CharField(blank=True, choices=[('vendor', 'Vendor'), ('cashier', 'Cashier'), ('pharmacist', 'Pharmacist'), ('doctor', 'Doctor'), ('inventory_manager', 'Inventory Manager'), ('pharmacy_manager', 'Pharmacy Manager'), ('platform_admin', 'Platform Administrator')], max_length=24, null=True, verbose_name='User Type')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Invitation Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expiration_date', models.DateTimeField(blank=True, default=accounts.models.get_default_invitation_expiration, null=True, verbose_name='Expiration Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_invitations', to='organizations.organization')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitations_received', to=settings.AUTH_USER_MODEL, verbose_name='Invitation Receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='Invitation Sender')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'User Invitation',
                'verbose_name_plural': 'User Invitations',
                'constraints': [models.UniqueConstraint(fields=('receiver_email', 'user_type', 'organization'), name='unique_invitation')],
            },
        ),
    ]
