# Generated by Django 5.2.1 on 2026-05-14 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_allowed_organizations_and_more'),
        ('organizations', '0001_initial'),
        ('pharmacies', '0006_productsubcategory_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'organization')},
        ),
        migrations.AddField(
            model_name='userrole',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='pharmacies.pharmacy'),
        ),
        migrations.AlterField(
            model_name='role',
            name='user_type',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('vendor', 'Vendor'), ('cashier', 'Cashier'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('doctor', 'Doctor'), ('auditor', 'Auditor'), ('accountant', 'Accountant'), ('finance_manager', 'Finance Manager'), ('inventory_manager', 'Inventory Manager'), ('pharmacy_manager', 'Pharmacy Manager'), ('platform_admin', 'Platform Administrator')], editable=False, max_length=24, verbose_name='User Type'),
        ),
    ]
