# Generated by Django 5.2.1 on 2026-05-15 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userrole_unique_together_userrole_pharmacy_and_more'),
        ('organizations', '0001_initial'),
        ('pharmacies', '0008_alter_historicalsale_status_alter_sale_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='pharmacies',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_invitations', to='pharmacies.pharmacy'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='pharmacies',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_roles', to='pharmacies.pharmacy'),
        ),
        migrations.AlterField(
            model_name='role',
            name='user_type',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('vendor', 'Vendor'), ('cashier', 'Cashier'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('doctor', 'Doctor'), ('auditor', 'Auditor'), ('accountant', 'Accountant'), ('finance_manager', 'Finance Manager'), ('inventory_manager', 'Inventory Manager'), ('pharmacy_manager', 'Pharmacy Manager'), ('platform_admin', 'Platform Administrator')], max_length=24, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='user_type',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('vendor', 'Vendor'), ('cashier', 'Cashier'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('doctor', 'Doctor'), ('auditor', 'Auditor'), ('accountant', 'Accountant'), ('finance_manager', 'Finance Manager'), ('inventory_manager', 'Inventory Manager'), ('pharmacy_manager', 'Pharmacy Manager'), ('platform_admin', 'Platform Administrator')], max_length=24, verbose_name='User Type'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_org_role'),
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='pharmacy',
        ),
    ]
