# Generated by Django 5.2.1 on 2026-05-16 16:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        ('organizations', '0001_initial'),
        ('pharmacies', '0008_alter_historicalsale_status_alter_sale_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=False, editable=False, verbose_name='Is Active')),
                ('account_type', models.CharField(choices=[('bank', 'Bank Account'), ('cash_drawer', 'Cash Drawer')], max_length=40, verbose_name='Account Type')),
            ],
            options={
                'verbose_name': 'Financial Account',
                'verbose_name_plural': 'Financial Accounts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='financialaccount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='financialaccount',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='financialaccount',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='financialaccount',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='financialaccount',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='financialaccount',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='cash_account',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='financial_account',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cash_account',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='financial_account',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Current Balance'),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='account_type',
            field=models.CharField(choices=[('cash_drawer', 'Cash Drawer'), ('mobile_money', 'Mobile Money')], max_length=20, verbose_name='Cash Account Type'),
        ),
        migrations.AlterField(
            model_name='currencydenomination',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='proof_file',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Proof File'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='finances/payments/proof_files', verbose_name='Proof File'),
        ),
        migrations.AddConstraint(
            model_name='currencydenomination',
            constraint=models.UniqueConstraint(fields=('currency', 'value'), name='unique_currency_denomination'),
        ),
        migrations.AddField(
            model_name='operationaccount',
            name='bank_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_account', to='finances.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AddField(
            model_name='operationaccount',
            name='cash_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_account', to='finances.cashaccount', verbose_name='Cash Account'),
        ),
        migrations.AddField(
            model_name='operationaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='operationaccount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization', verbose_name='Related Organization'),
        ),
        migrations.AddField(
            model_name='operationaccount',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_accounts', to='pharmacies.pharmacy', verbose_name='Pharmacy'),
        ),
        migrations.AddField(
            model_name='operationaccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='operation_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finances.operationaccount', verbose_name='Operation Account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='operation_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finances.operationaccount', verbose_name='Operation Account'),
        ),
        migrations.AlterField(
            model_name='financialoperation',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_operations', to='finances.operationaccount', verbose_name='Destination Account'),
        ),
        migrations.AlterField(
            model_name='financialoperation',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_operations', to='finances.operationaccount', verbose_name='Source Account'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialoperation',
            name='destination_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finances.operationaccount', verbose_name='Destination Account'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialoperation',
            name='source_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finances.operationaccount', verbose_name='Source Account'),
        ),
        migrations.DeleteModel(
            name='FinancialAccount',
        ),
    ]
