# Generated by Django 5.2.1 on 2026-05-17 23:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_operationaccount_and_more'),
        ('organizations', '0002_organization_city_organization_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('-is_active', '-is_default_for_country', 'name'), 'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.RemoveField(
            model_name='currency',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='currencydenomination',
            name='organization',
        ),
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.CharField(blank=True, choices=[('BJ', 'Benin'), ('BF', 'Burkina Faso'), ('CI', "Côte d'Ivoire"), ('GW', 'Guinea-Bissau'), ('ML', 'Mali'), ('NE', 'Niger'), ('SN', 'Senegal'), ('TG', 'Togo'), ('CM', 'Cameroon'), ('CF', 'Central African Republic'), ('TD', 'Chad'), ('CG', 'Congo'), ('GQ', 'Equatorial Guinea'), ('GA', 'Gabon'), ('GH', 'Ghana'), ('NG', 'Nigeria'), ('XX', 'Other / Regional')], help_text='Main market for this currency entry.', max_length=2, null=True, verbose_name='Primary Country'),
        ),
        migrations.AddField(
            model_name='currency',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(default=2, editable=False),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_default_for_country',
            field=models.BooleanField(default=False, help_text='Auto-selected when organization picks this country.', verbose_name='Default for Country'),
        ),
        migrations.AddField(
            model_name='currency',
            name='preset',
            field=models.CharField(blank=True, choices=[('XOF', 'West African CFA Franc'), ('XAF', 'Central African CFA Franc'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound')], help_text='ISO 4217 code. Locked after creation.', max_length=3, null=True, unique=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive currencies are hidden from selection.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.CreateModel(
            name='OrganizationCurrency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Reporting Currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_symbol_first', models.BooleanField(default=True, help_text='₦500 vs 500 ₦', verbose_name='Symbol Before Amount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_links', to='finances.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('organization',), name='one_active_default_per_org')],
                'unique_together': {('organization', 'currency')},
            },
        ),
    ]
